server:
  servlet:
    context-path: /api/content-service
  port: 6787

keycloak:
  realm: SocialNetworkRealm
  auth-server-url: http://localhost:8080/
  ssl-required: external
  resource: social-network
  use-resource-role-mappings: true
  bearer-only: true
  public-client: true

spring:
  main:
    allow-bean-definition-overriding: true #cho phép việc ghi đè (overriding) các bean trong ứng dụng
  application:
    name: content-service
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/changes/db.changelog-master.xml
    default-schema: public
  datasource:
    url: jdbc:postgresql://localhost:5432/db_fb_clone_service_content
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: content-service
      connection-timeout: 30000 #thời gian tối đa (tính = millisecond) mà client đợi để kết nối
      minimum-idle: 2 #số kết nối tối thiểu mà pool luôn giữ trong trạng thái rảnh (idle)
      maximum-pool-size: 20 #số lượng tối đa mà pool có thể quản lý
      idle-timeout: 10000 #thời gian tối đa mà connection idle(không sử dụng) sẽ được giữ trước khi bị loại bỏ
      max-lifetime: 30000 #thời gian tối đa mà một connection được phép tồn tại trước khi bị loại bỏ, bất kể có đang được sử dụng hay không
      auto-commit: true #các thay đổi trong giao dịch sẽ đuợc tự động commit sau mỗi câu lệnh
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    hibernate:
      ddl-auto: none
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 3MB
service-user:
  base-url: http://localhost:6789/api/user-service
default:
  image:
    url-avatar-user: https://scontent.fhan3-5.fna.fbcdn.net/v/t39.30808-6/315373443_877129556799105_6340277356280668501_n.jpg?_nc_cat=107&ccb=1-7&_nc_sid=6ee11a&_nc_ohc=lopTYYMk0j4Q7kNvgF4rhoo&_nc_oc=AdhH8ZuEtRJHeuPQfEyFLjbf2Y5GBp1CxVnV-0tsz2jeYlAeyxQ9WGlCbyx9qhuSGZEaiqm3KSK-80y4-OaGSgeS&_nc_zt=23&_nc_ht=scontent.fhan3-5.fna&_nc_gid=AA8kpH6CVbOUzmiUw5bJO3A&oh=00_AYB6kPaBH1V9e6S5M_jAuhnXqR8xsGTq950YTG8lLbh_mQ&oe=67A41ADE
